# The config version of the file.
config-version: 1.0.0.0
# The locale file to use, without the file extension.
locale: en_US
# Should any enchantments not applied be given back as a new enchanted book?
give-enchanted-book-for-unapplied-enchantments: false
# If the above setting is true, should enchantments be given as one book or multiple?
give-unapplied-enchantments-as-one-book: true